import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { TERMS_DOC, PRIVACY_DOC } from "@/lib/legal/docs";
import { AcceptTermsCard } from "./accept-terms-card";

// `next` reaches here as a plain query param on every request, regardless
// of whether it was generated by requireCurrentAgreement's own redirect —
// a visitor can hand-edit the URL, so this can't be trusted as-is. Resolved
// against a fixed internal base and compared by origin (not a startsWith
// string check) so WHATWG URL normalization — e.g. a literal backslash in
// "/\evil.com" becomes "//evil.com" and changes origin — can't sneak an
// open redirect past a naive "//" prefix check.
function safeNext(next: string | string[] | undefined): string {
  const value = Array.isArray(next) ? next[0] : next;
  if (!value) return "/";
  try {
    const resolved = new URL(value, "http://internal.invalid");
    if (resolved.origin !== "http://internal.invalid") return "/";
    return resolved.pathname + resolved.search + resolved.hash;
  } catch {
    return "/";
  }
}

export default async function AcceptTermsPage({
  searchParams,
}: {
  searchParams: Promise<{ next?: string | string[] }>;
}) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { next } = await searchParams;

  return (
    <div className="flex min-h-full items-center justify-center px-4 py-16">
      <AcceptTermsCard
        termsVersion={TERMS_DOC.version}
        termsEffectiveDate={TERMS_DOC.effectiveDate}
        privacyVersion={PRIVACY_DOC.version}
        privacyEffectiveDate={PRIVACY_DOC.effectiveDate}
        next={safeNext(next)}
      />
    </div>
  );
}
