-- C3: availability-driven booking. Services no longer need a tutor-created
-- booking_links row to be bookable — the public tutor page (Q3) offers each
-- active service directly, with open times computed straight from the
-- tutor's weekly availability (C2) filtered by that service's duration,
-- reusing B4's is_slot_bookable() so nothing double-books against sessions
-- OR bookings either way in. This is deliberately NOT built on top of
-- booking_links (B4's "standing link" mode already does something similar,
-- but only once a tutor explicitly creates one) — C3's spec is explicit
-- that "a service by itself never defines times" but the PUBLIC PAGE should
-- offer availability-driven booking by default, with no link/token as a
-- prerequisite. Reusing booking_links here would mean auto-creating one
-- invisible row per service behind the tutor's back, cluttering their
-- Booking Links list with links they never consciously made — instead this
-- keys every check off (tutor handle, service id) directly. B4's manual
-- "offer specific slots" link (and its standing-availability mode) stay
-- exactly as they are: an explicit, tutor-initiated, optional secondary
-- path (get_public_tutor_profile's `booking_token` field), unchanged.
--
-- No buffer_minutes here (unlike B4's booking_links, which lets the tutor
-- set one per link) — there's no per-service creation step for the tutor to
-- set a buffer on. TODO(connor): if back-to-back bookings turn out to be a
-- problem, the natural home for a buffer setting is a new tutors-level
-- default (e.g. `default_booking_buffer_minutes`), not a per-service field.

-- Adds `id` (needed so the public page can link to /t/[handle]/book/[id])
-- to each service in the existing json shape — additive, same signature,
-- CREATE OR REPLACE like every other widening of this function so far.
create or replace function get_public_tutor_profile(p_handle text)
returns json
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_tutor tutors%rowtype;
  v_services json;
  v_booking_token text;
begin
  select * into v_tutor from tutors where lower(handle) = lower(p_handle) and is_public;
  if v_tutor.id is null then
    return json_build_object('found', false);
  end if;

  select coalesce(
    json_agg(
      json_build_object(
        'id', s.id,
        'name', s.name,
        'description', s.description,
        'duration_minutes', s.duration_minutes,
        'price_cents', case when v_tutor.show_prices then s.price_cents else null end
      )
      order by s.created_at
    ),
    '[]'::json
  )
  into v_services
  from services s
  where s.tutor_id = v_tutor.id and s.is_active;

  select bl.token into v_booking_token
  from booking_links bl
  where bl.tutor_id = v_tutor.id
    and bl.status = 'open'
    and bl.student_id is null
    and (bl.service_id is null or exists (
      select 1 from services sv where sv.id = bl.service_id and sv.is_active
    ))
    and (
      bl.mode = 'open_availability'
      or exists (select 1 from booking_link_slots s where s.booking_link_id = bl.id and s.start_ts > now())
    )
  order by bl.created_at desc
  limit 1;

  return json_build_object(
    'found', true,
    'name', v_tutor.name,
    'bio', case when v_tutor.show_bio then v_tutor.bio else null end,
    'subjects', v_tutor.subjects,
    'services', v_services,
    'booking_token', v_booking_token
  );
end;
$$;

-- Public read: tutor + service header info for the /t/[handle]/book/[id]
-- page. Separate from get_public_tutor_profile (which lists ALL services)
-- since this page only needs the one being booked, keyed by id directly —
-- avoids re-fetching and re-scanning the full service list client-side.
create function get_public_service(p_handle text, p_service_id uuid)
returns json
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_tutor tutors%rowtype;
  v_service services%rowtype;
begin
  select * into v_tutor from tutors where lower(handle) = lower(p_handle) and is_public;
  if v_tutor.id is null then
    return json_build_object('found', false);
  end if;

  select * into v_service from services where id = p_service_id and tutor_id = v_tutor.id and is_active;
  if v_service.id is null then
    return json_build_object('found', false);
  end if;

  return json_build_object(
    'found', true,
    'tutor_name', v_tutor.name,
    'service_name', v_service.name,
    'description', v_service.description,
    'duration_minutes', v_service.duration_minutes,
    'price_cents', case when v_tutor.show_prices then v_service.price_cents else null end
  );
end;
$$;

-- Public read: open start times for one calendar date, generated by
-- striding through the tutor's weekly availability (C2) at the service's
-- duration and filtering through is_slot_bookable() (B4) — the exact same
-- generate-then-filter shape as get_open_availability_slots, just keyed by
-- (handle, service_id) instead of a booking_links token, and buffer fixed
-- at 0 (see the header comment above for why). Empty array for an
-- unpublished handle or inactive/unknown service, same calm-empty-state
-- convention as every other public lookup in this schema.
create function get_public_service_slots(p_handle text, p_service_id uuid, p_date date)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tutor tutors%rowtype;
  v_service services%rowtype;
  v_weekday integer;
  v_window record;
  v_candidate timestamptz;
  v_window_end timestamptz;
  v_slots timestamptz[] := '{}';
begin
  select * into v_tutor from tutors where lower(handle) = lower(p_handle) and is_public;
  if v_tutor.id is null then
    return json_build_object('slots', '[]'::json);
  end if;

  select * into v_service from services where id = p_service_id and tutor_id = v_tutor.id and is_active;
  if v_service.id is null then
    return json_build_object('slots', '[]'::json);
  end if;

  v_weekday := extract(dow from p_date);

  for v_window in
    select start_time, end_time from availability where tutor_id = v_tutor.id and weekday = v_weekday
  loop
    v_candidate := (p_date::text || 'T' || v_window.start_time::text || 'Z')::timestamptz;
    v_window_end := (p_date::text || 'T' || v_window.end_time::text || 'Z')::timestamptz;
    while v_candidate + (v_service.duration_minutes || ' minutes')::interval <= v_window_end loop
      if is_slot_bookable(v_tutor.id, v_candidate, v_service.duration_minutes, 0) then
        v_slots := array_append(v_slots, v_candidate);
      end if;
      v_candidate := v_candidate + (v_service.duration_minutes || ' minutes')::interval;
    end loop;
  end loop;

  return json_build_object(
    'slots',
    (select coalesce(json_agg(t order by t), '[]'::json) from unnest(v_slots) as t)
  );
end;
$$;

-- Public write: confirms a (re-validated, never trusted from the client)
-- open time for a service directly — same shape as confirm_open_booking_link
-- (advisory lock BEFORE the is_slot_bookable check, so two parents racing
-- for the same time can't both pass; create-or-link the student the same
-- way) but keyed by (handle, service_id) and with no booking_links row to
-- touch at all.
create function confirm_public_service_booking(
  p_handle text,
  p_service_id uuid,
  p_start_ts timestamptz,
  p_parent_name text,
  p_parent_email text,
  p_student_name text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tutor tutors%rowtype;
  v_service services%rowtype;
  v_client_id uuid;
  v_client clients%rowtype;
  v_effective_rate integer;
  v_bill_travel boolean;
  v_travel_rate integer;
  v_session_id uuid;
  v_code text;
  v_alphabet text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  v_attempts integer := 0;
  i integer;
begin
  if p_parent_email is null or btrim(p_parent_email) = '' then
    raise exception 'Email is required.';
  end if;
  if p_student_name is null or btrim(p_student_name) = '' then
    raise exception 'Student name is required.';
  end if;

  select * into v_tutor from tutors where lower(handle) = lower(p_handle) and is_public;
  if v_tutor.id is null then
    raise exception 'This tutor page is no longer available.';
  end if;

  select * into v_service from services where id = p_service_id and tutor_id = v_tutor.id and is_active;
  if v_service.id is null then
    raise exception 'This service is no longer offered — ask your tutor for an up to date link.';
  end if;

  -- Tutor-wide lock BEFORE the availability/overlap check — same fix as
  -- confirm_open_booking_link (B4) / create_booking (P9): the lock, not the
  -- statement shape, is what makes this SELECT-then-INSERT safe under
  -- concurrent confirms for the same tutor.
  perform pg_advisory_xact_lock(hashtext(v_tutor.id::text)::bigint);

  if not is_slot_bookable(v_tutor.id, p_start_ts, v_service.duration_minutes, 0) then
    raise exception 'That time is no longer available — pick another.';
  end if;

  -- No existing-student path here (unlike confirm_booking_link/
  -- confirm_open_booking_link, which can be pre-scoped to a specific
  -- student by the tutor at link-creation time) — the public page's
  -- default service flow is open to any visitor, so it always creates or
  -- matches on the parent's own account the same way B4's "open" links do
  -- when left unassigned: a brand new student + invite every time. A
  -- returning parent linking multiple bookings to the same existing
  -- student is exactly what the tutor-code join flow (Q7) is for.
  insert into clients (tutor_id, student_name, payer_name, payer_email, rate_type, scheduling_mode)
  values (
    v_tutor.id, btrim(p_student_name), nullif(btrim(p_parent_name), ''),
    lower(btrim(p_parent_email)), 'standard', 'message'
  )
  returning id into v_client_id;

  loop
    v_code := '';
    for i in 1..7 loop
      v_code := v_code || substr(v_alphabet, 1 + floor(random() * length(v_alphabet))::integer, 1);
    end loop;
    begin
      insert into invites (tutor_id, student_id, code, status)
      values (v_tutor.id, v_client_id, v_code, 'active');
      exit;
    exception when unique_violation then
      v_attempts := v_attempts + 1;
      if v_attempts > 5 then
        raise exception 'Could not generate a unique invite code — try again.';
      end if;
    end;
  end loop;

  select * into v_client from clients where id = v_client_id;

  v_effective_rate := v_tutor.standard_rate_cents;
  v_bill_travel := coalesce(v_client.bill_travel, v_tutor.bill_travel_default);
  v_travel_rate := coalesce(v_client.travel_rate_cents, v_tutor.travel_rate_cents, v_effective_rate);

  insert into sessions (
    tutor_id, client_id, occurred_on, start_time, duration_minutes,
    travel_minutes, bill_travel, effective_rate_cents, travel_rate_cents, status,
    service_id, service_price_cents
  )
  values (
    v_tutor.id, v_client_id,
    (p_start_ts at time zone 'utc')::date, (p_start_ts at time zone 'utc')::time,
    v_service.duration_minutes, 0, v_bill_travel, v_effective_rate, v_travel_rate, 'logged',
    v_service.id, v_service.price_cents
  )
  returning id into v_session_id;

  return json_build_object('session_id', v_session_id);
end;
$$;

revoke execute on function get_public_service(text, uuid) from public;
revoke execute on function get_public_service_slots(text, uuid, date) from public;
revoke execute on function confirm_public_service_booking(text, uuid, timestamptz, text, text, text) from public;

grant execute on function get_public_service(text, uuid) to anon, authenticated;
grant execute on function get_public_service_slots(text, uuid, date) to anon, authenticated;
grant execute on function confirm_public_service_booking(text, uuid, timestamptz, text, text, text) to anon, authenticated;
-- get_public_tutor_profile keeps its existing grant (CREATE OR REPLACE
-- carries it forward) — no new grant needed.
