// A `next` redirect target reaches app code as a plain query param —
// generated by our own redirects (lib/legal/gate.ts, middleware's login
// redirect) but also directly hand-editable by any visitor, so it can never
// be trusted as-is. Resolved against a fixed internal base and compared by
// origin (not a startsWith string check) so WHATWG URL normalization — e.g.
// a literal backslash in "/\evil.com" becomes "//evil.com" and changes
// origin — can't sneak an open redirect past a naive "//" prefix check.
// Pure (no server/client-only APIs), so it works from both a Server
// Component's searchParams and a Client Component's useSearchParams().
export function safeNext(next: string | string[] | null | undefined, fallback = "/"): string {
  const value = Array.isArray(next) ? next[0] : next;
  if (!value) return fallback;
  try {
    const resolved = new URL(value, "http://internal.invalid");
    if (resolved.origin !== "http://internal.invalid") return fallback;
    return resolved.pathname + resolved.search + resolved.hash;
  } catch {
    return fallback;
  }
}
